plugin: yc_compute
folders:
  - b1grhssq464f0hsjkphd
auth_kind: serviceaccountfile
service_account_file: ~/.yc/key.json
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
keyed_groups:
  - key: labels['tags']
