dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: WKrsYf7ptnfl/xTnwV9oS/OnUcNe58ktUnQrWZjuzTGFaP1zl19zgYvsuRDd52XWMV7mBK+eZo/d2tlRPZL5D30aLKUeEbarLwhnumq/VIzu35orn3kAU6ao/+0vg4F0h3FcjtXRgu6lbvyvmFjie7Ep6asmTBlttpGC1cfR0dm2RRZ3zALvMufFap5vrcdwGEJAAo5tEd81n8qT7KQ09qtvsEi6hyxBxMxy9sey3cdE9Diqe25fy+Sj+6pKvALWsUicDAy5+WhlLz4PKbWi7pNSct4Ke959S9ixmXKBohZNHsNjq8/TA2J9azYGmA5V4BdF9TXKh++dkzCvd9uHM70QdOLvH3Rr4VvndiuuHCmqWddSshT90acERhU0g6tV62K55OCiMpcc7OjBN+k93u7Dq/1pWrUx9Ue4ksMqU8l7g3iNQQgjpfVZydJfTZAw73dSDSegduzqVMkfVZvsoKAwcKjLrMx8DI36IAbRLGXhJi1tsCQnEywp+1BJyZ0dXzvPZm320O8lqS6asarsP0xwS74D2M+OqlyMkqPnRQoHJinLmX3b18m5+BzF+IgbA6tcnJw1PjQfelpO9XZ9HmV8xDZqeRpXQ9FlH0/84y+Qi5ZG1a/Vk8dhSTO0o4PsMVuz5ghZyeaCa1jsylybIgMcnZQHrZCnoOPo2Zon5rg=
