dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "QnclHrfr00hzIpqLUgyVLs9hKyxyLUTvNFM7VZQ+PoiEvEuiUQ3UCXLJOO9i9coaA2y2xKarwC1QH1l7GcsEw4l6VEvVuWEu3FAVXYJh3nzrYgcjJ1Z5oqXGEEQdK2gmLRCXztDJUPCMJkc9JlwI8iEKrWov+293TabRzMRZY9dqL7HrRbeB3tylnob0kVEEdpQIE3SnaxgZI07xhoUfqIXSTl+KnOs3gBbKULPJbC6YZw9m1IHG4TZbT4PwUQhz2niy0/A+HaLlO8cJGDolV0K2y5jTQo3kg/98kn9lIB7xmOWaIeB3LmeYktABwL4ADuxLmC0hLNtIdK1WSRcfPdxTfpAruHrXHTjvQMxesoZ1+VPhK4X49mxayL+MDeL5NCJrYLUYEPFaUKNd0fn0hrA6Zh1x+nizTlv5FSDkF0o1j5Wo6ooFgY+4XC/eJpoXiWPZnaUfC0mL8/fM/lEYJsOgHl00vjGqRMcuBmohnp8VHcyq2KR0KRVshg7SxtxOEe9NMcFU9QJ/de7upExzmXFi46uyM+f7/Tm2S5Yj6tf9JlQex2UDLX82Pz4FcdZewvIeYTtQ/3uB1sE0XzOPaXKI/gGyF4rkLzuQ2N6U4Qp+hQQhvWk2NqkYlpg10IO2jEMHfNj6i6ErkXUIzkgbW4PapTJ39EFMMhTQTLvavlI="
