dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure:
W0i0AOVFIq9MtXl4JD1vrKEV4KU+5OE9mrtjMC4OxGfA9r9ra2YXjodlcntE/SOok6re8HZUj86LhnRvW6w3FiggAimQ8kd7DujLgv6VA4YsfAvxxFIn7m92DjHMkzLR+FfJ2sAFBnqA9BcXO7BMJxCvkzkMivZz8MsNol/94ALdrqdnlotFfmHigmZvtcqBHZPqLEK1xC8VNkOG5JdmwGCRNmeIYyqlf4azVQzjBgQFYT8gTTO3kz/sNJuv2rEnRPtzuwGvtmddC2UFBzCEdcZrBizYRLYEERrCRiJHH2GdolAT3a7FTzdDJaG0lv58j1KXulWUXNMB5I7g4vsx8gc7Ix5mF9AFzchrvm/oOw1IJlGkLVU2vbhACfv4++BGodiWOCAyEuxc691JJBDwYzOpkxziv65s8+c/JbhuKXwaIasifxtjvrR7SgNgUQHbU1uLyWTmipVA4D9gmf3weNreWnTjy96gwZUuyIp4Ajgeu3g1/0gtO3JzuqT+zpH+qoLCFgerq2frOzNWGJm3YYZt4N4AkdNCorMAqnYG23zgnhVMIGcRJ4mFtiDdkfcf6NZHefO2JCGKj7fctnk+sQW3tqAZ6rb16hpN/lVVuUT8JHp2jnKavPwFz4qlNDQgDAncQKK/GkgDGWXlFn7o64kF0lcZcLpmvhslg1Pc54Y=
