---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install python for Ansible
      raw: "{{ item }}"
      loop:
        - sudo apt install -y python-minimal
      changed_when: False
