---
- name: Install MongoDB 4.2
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add repository
      apt_repository:
        repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        state: present

    - name: Apt-get update
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present
        allow_unauthenticated: yes

    - name: Enable service
      systemd:
        name: mongod
        enabled: yes
